<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>bf7acb2b-826c-4afd-8f94-ac4aa849855f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireApp9.Server\AspireApp9.Server.csproj" />
    <ProjectReference Include="..\AspireApp9.Yarp\AspireApp9.Yarp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.5" />
  </ItemGroup>
</Project>
